# Generated by Django 3.1 on 2020-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='product_id',
            new_name='query_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.AddField(
            model_name='contact',
            name='query',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
