# Generated by Django 3.1 on 2020-09-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0002_auto_20200831_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ratings',
            field=models.CharField(default='5', max_length=10),
        ),
    ]
