# Generated by Django 3.1 on 2020-09-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0008_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel1',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(default='', upload_to='Review/images')),
                ('image2', models.ImageField(default='', upload_to='Review/images')),
                ('image3', models.ImageField(default='', upload_to='Review/images')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel2',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.ImageField(default='', upload_to='Review/images')),
                ('image2', models.ImageField(default='', upload_to='Review/images')),
                ('image3', models.ImageField(default='', upload_to='Review/images')),
            ],
        ),
    ]
