# Generated by Django 3.1 on 2020-09-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0009_carousel1_carousel2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel1',
        ),
        migrations.DeleteModel(
            name='Carousel2',
        ),
    ]
