# Generated by Django 3.1 on 2020-09-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(default='', max_length=50)),
                ('dprice', models.IntegerField(default=0)),
            ],
        ),
    ]
