# Generated by Django 3.1 on 2020-09-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0013_menu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Querie',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('query', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='Dishe',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
