# Generated by Django 3.1 on 2020-09-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReviewApp', '0016_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishe',
            name='category',
            field=models.CharField(choices=[('Curries', 'Curries'), ('Fish Fry', 'Fish Fry'), ('Biryani', 'Biryani'), ('Veg', 'Veg'), ('Misc', 'Misc')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ReviewApp/images'),
        ),
    ]
